{% set name = "mc-goods" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mc_goods-{{ version }}.tar.gz
  sha256: 027b00f3dcfe90f9148f57ec82a0ccc3c06b861d2b2e8e440902edb71ddeb0d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.6
    - intake

test:
  imports:
    - mc_goods
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/mc-goods
  summary: model_catalogs catalogs for GOODS
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
